#ifndef DBUSDEVICE_H
#define DBUSDEVICE_H

#include <QString>
#include <QStringList>

class DbusDevice
{
public:
    DbusDevice();

    // all public!
    QString DeviceFile;  // something like this: /dev/${IdUuid} or /dev/${IdLabel}
    QString IdLabel;     // the filesystem label if there is one
    QString IdUuid;      // will be generated by the kernel and should always be there
    QString IdType;      // the filesystem type (vfat, ntfs, etc. pp.)
    QString ObjectPath;  // thats the DBUS path /org/...
    QString MountedPath; // where the system has mounted the filesystem
    QString LastError;   // stores the error message when a device error occured

    QString theObjectPath() const;
    QString theLabel() const;
    QString theMountedPath() const;
};

#endif // DBUSDEVICE_H
